apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ww-gitops
  namespace: flux-system
spec:
  interval: 1m
  url: "oci://ghcr.io/weaveworks/charts"  # Ensure this URL is correct
