apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellogo
  labels:
    app: hellogo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hellogo
  template:
    metadata:
      labels:
        app: hellogo
    spec:
      containers:
      - name: hellogo
        image: hellogo:d10fa0c0452b73cc75d1b15b4777ca1f2bd07bad01c1698e45bb119b65b2ccec
        ports:
        - containerPort: 8080  # Assurez-vous que ce port est le bon pour votre application
